.circleci/circle-lock.sh, .circleci/config.yml
When deploying more than one of these projects to a single account, we need to qualify the stage name.
STAGE_PREFIX set at the project settings level accomplishes that.
Also including an update to the lock script to dynamically figure out the circle ci api url
=> Set stage prefix for shared accounts and determine api url

.circleci/circle-lock.sh, .circleci/config.yml, .gitignore, tests/test.sh
This is a simple smoke test using testcafe.
I was hoping to use Cypress, but this is quick and easy.
Maybe have several frameworks ready to go in the repo, and the user can just choose.
Test results are archived as a build artifact.
Closes #14
=> Add Smoke Tests

.circleci/config.yml
Closes #21 
This introduces a simple pattern for promoting code.  
All branches are built and deployed, except those that begin with skipci.
Deploying prod would be a merge from master to a branch called prod, which should be a protected branch.
Merge to prod and prod deploys.
The injection of prod specific environment variables is still supported with the 'set environment for deploy' block; that's unchanged.
What are the drawbacks here?  
- There's no decay; environments are built, but not automatically removed at end of life.  A developer or admin needs to run the destroy.sh script against built environments to take them down.
What's good?
- This is dirt simple.  All branches are built, unless you prefix it with skipci.
- All pull requests will show a status check from CCI.  Code can't …
=> Build all branches except those beginning with skipci

.circleci/config.yml
Since the introduction of 'build all branches', we are no longer filtering for bad branches at the circle ci level.
In other words, someone can push a branch called this_wont_work_with_serverless and it will run in CircleCI.. the underscores will break serverless when it gets to deployment.
This introduces some logic to verify the branch name will work with serverless.
Without this, serverless would fail and print an error message... and that's totally fine, but it might be confusing for unfamiliar developers.
The hope is that this fast failure and (i hope) nicely written error message with an explanation will click with a developer and guide him/her to the remedy.
=> Verify branch name before deployment

services/app-api/serverless.yml, services/database/serverless.yml, services/elasticsearch-auth/serverless.yml, services/elasticsearch/serverless.yml, services/stream-functions/serverless.yml, services/ui-auth/serverless.yml
Closes #9 
Greenfield accounts have users restricted to IAM operations inside a given path.  
Roles must also be created with a certain permissions boundary specified.
These changes allow for IAM_PERMISSIONS_BOUNDARY_ARN and IAM_PATH to be specified as environment variables... these settings will globally create all IAM objects at that path and with that boundary
The permissions boundary ARN should be converted to just the permissions boundary policy name; the arn can be predicted since it's form is known.  That can be handled in a future issue.  And on that note, the SES_SOURCE_EMAIL_ARN should also be generated from the source email and the arn's known form.
=> Adapt code to work with CMS Greenfield IAM restrictions

.circleci/config.yml, package-lock.json, package.json
Cache and reuse testcafe and serverless.  It saves approx 40 seconds per build when not missing the cache.
We need version 2.1.
=> Cache serverless and testcafe

.circleci/package.json, deploy.sh, package.json, services/app-api/package-lock.json, services/app-api/package.json, services/database/package-lock.json, services/database/package.json, services/elasticsearch-auth/package-lock.json, services/elasticsearch-auth/package.json, services/elasticsearch-config/package-lock.json, services/elasticsearch-config/package.json, services/elasticsearch/package-lock.json, services/elasticsearch/package.json, services/stream-functions/package-lock.json, services/stream-functions/package.json, services/ui-auth/package-lock.json, services/ui-auth/package.json, services/ui-src/package-lock.json, services/ui-src/package.json, services/ui/package-lock.json, services/ui/package.json, services/uploads/package-lock.json, services/uploads/package.json
This standardized the monorepo's services' structure.  Each has a package.json and lock, whether or not it has node dependencies.  There's no time hit in doing this, and it simplifies install logic.
Logic in deploy.sh was added to ensure that if a developer runs deploy.sh, dependencies are installed via npm install.
If a CI system runs deploy.sh, the existence of node_modules in a given directory is taken as an indication of a cache hit/miss.  Dependencies are therefore installed via npm ci if no node_modules is present.
=> Standardize service structure

.circleci/config.yml, .circleci/set_vars.sh
Closes #54 
set_vars.sh has been added to the .circleci folder.
It contains a list of environment variables that we may want to override on a per branch basis.
For example:
Setting master_SES_SOURCE_EMAIL_ADDRESS=actualprod@cms.gov as a circleci project environment variable will apply that value of SES_SOURCE_EMAIL_ADDRESS on the master branch only.  In this way, you may specify specific values for specific branches.
If you want to set a value for a certain branch, and default all other branches to another value, the recommended pattern is:
- set SES_SOURCE_EMAIL_ADDRESS=adefaultemail@cms.gov in CircleCI.  This will apply to all branches.
- set master_SES_SOURCE_EMAIL_ADDRESS=myrealprodemail@cms.gov in CircleCI.  This will be set on the master branch only, for example, and override that …
=> Add a script to set any of a list of branch specific env vars

.circleci/set_vars.sh
Closes #56 
I realized I closed this issue without addressing non-cloudtamer accounts, which would use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY instead of CTKEY variables.
=> Deploy to different AWS Accounts - add support for non-cloudtamer accts

services/app-api/package-lock.json, services/app-api/package.json, services/app-api/serverless.yml
Closes #67 
2 things here:
- #67 bug fix... The generated warmup handler was not in the place the copy-webpack expected it to be.  This can be resolved a few ways, but the easiest was decided to be by telling the warmup plugin to generate the handler at the expected path.
- The third line in the handler the warmup plugin generates is essentially a timestamp.  Therefore, redeploying the app-api service with no real changes would still force a stack update, since the warmup function's source code changed slightly (timestamp).  This was solved by running a hook before packaging is finalized... the hook finds the timestamp line and removes it with sed.
This should drop the no-op build time on master / INFRASTUCTURE_TYPE=prod branches by about 30 seconds
=> Fix warmup bug and make warmup deployments idempotent

services/elasticsearch/serverless.yml
There's logic in the quickstart... when INFRASTRUCTURE_TYPE=production, there's a few places where we build bigger/more highly provisioned infra.  This is to demonstrate a way to conditionally build different infra for different requirements.
Well, elasticsearch isn't exactly cheap.  So I want to reel in the size of the INFRASTRUCTURE_TYPE=production ES cluster.
I'm leaving the logic and switch in place, it's just the same value for both cases.  So someone should be able to easily modify this to build the sizes they want.
=> Reduce the elasticsearch instance type for production envs

services/elasticsearch/serverless.yml
We're reducing the production ES infrastructure to save on our own costs.
Real world, encryption would be on and instance size would be larger and scaled out.
The logic is all there for INFRASTRUCTURE_TYPE=production, so it should be obvious how to modify it
=> Reduce ES cost - set encryption to false for smaller instance usage

destroy.sh
Closes #79 
The stacks and buckets are sufficiently tagged out of the box.  No need to tag them ourselves.
This is a much better way to approach destroying, see issue for details.
=> Improve destroy capability 

.github/build_vars.sh, .github/workflows/deploy.yml, .github/workflows/destroy.yml
Closes #72 
See issues for details.  In short, Github Actions is deprecating set-env on Monday.  It was straightforward to move to an environment file.  The environment file approach is nearly identical to CircleCI.
There is no impact to how you are settings secrets and per-branch env variables.  The only difference is exactly how they are persisted throughout the build.  You do not need to make secrets updates on account of this PR.
=> Update workflows for set-env deprecation

.github/workflows/destroy.yml, destroy.sh, package.json, services/app-api/serverless.yml, services/database/serverless.yml, services/elasticsearch-auth/serverless.yml, services/elasticsearch/serverless.yml, services/stream-functions/serverless.yml, services/ui-auth/serverless.yml, services/ui-src/serverless.yml, services/ui/serverless.yml, services/uploads-scan/serverless.yml, services/uploads/serverless.yml, yarn.lock
Safety checks were added to destroy.yml and destroy.sh to prevent the deletion of important branches
The version of serverless was upgraded to ^2.7.0.  I'm really unclear why it was at 1.82.0, because I could have sworn it was upgraded to 2.x awhile ago.
Styling changes were made, and services were standardized.
This will undoubtedly cause conflicts on existing branches that have diverged, but there's only 1 (local dev) and I'm going to be hands on or working with who's hands on, and the conflicts are simple.
=> Serverless upgrade, safety, and style

.github/workflows/destroy.yml, destroy.sh, package.json, services/app-api/serverless.yml, services/database/serverless.yml, services/elasticsearch-auth/serverless.yml, services/elasticsearch/serverless.yml, services/stream-functions/serverless.yml, services/ui-auth/serverless.yml, services/ui-src/serverless.yml, services/ui/serverless.yml, services/uploads-scan/serverless.yml, services/uploads/serverless.yml, yarn.lock
Safety checks were added to destroy.yml and destroy.sh to prevent the deletion of important branches
The version of serverless was upgraded to ^2.7.0. I'm really unclear why it was at 1.82.0, because I could have sworn it was upgraded to 2.x awhile ago.
Styling changes were made, and services were standardized.
This will undoubtedly cause conflicts on existing branches that have diverged, but there's only 1 (local dev) and I'm going to be hands on or working with who's hands on, and the conflicts are simple.
=> Serverless upgarde, safety and style

.github/workflows/deploy.yml, services/app-api/package.json, services/app-api/serverless.yml, services/app-api/yarn.lock, services/database/package.json, services/database/serverless.yml, services/database/yarn.lock, services/elasticsearch-auth/package.json, services/elasticsearch-auth/serverless.yml, services/elasticsearch-auth/yarn.lock, services/elasticsearch/package.json, services/elasticsearch/serverless.yml, services/elasticsearch/yarn.lock, services/stream-functions/package.json, services/stream-functions/serverless.yml, services/stream-functions/yarn.lock, services/ui-auth/package.json, services/ui-auth/serverless.yml, services/ui-auth/yarn.lock, services/ui-src/package.json, services/ui-src/serverless.yml, services/ui-src/yarn.lock, services/ui/package.json, services/ui/serverless.yml, services/ui/yarn.lock, services/uploads/package.json, services/uploads/serverless.yml, services/uploads/yarn.lock
Closes #113 
Closes #107 
This adds cloudformation termination protection for a list of stage names that are commonly used for important environments.  This has the effect of requiring a --force flag to be set if destroying a protected stage with serverless (something we never do programatically, so a human would need to set that).  In the console, to delete a protected stack, the termination protection must be manually edited to be disabled. 
We have a few safeguards in place to prevent deletion of important stages, but this is a huge add since it's protection baked into cloudformation itself.
```  serverlessTerminationProtection:
stages: # This is a list of common names for important envs that should not be destroyed.  You can remove the stage names your project doesn't use; this list …
```
=> Add termination protection and refactor GHA caching

.github/workflows/deploy.yml, .github/workflows/destroy.yml
This PR enables our standard CI support for dependency security updates that are automatically generated by Dependabot.
Closes #133 
[Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) is a GitHub native tool that is capable of scanning source code for package vulnerabilities.  Once enabled, Dependabot will scan the default branch for listed dependencies in package.json and yarn.lock files.  If a vulnerable package version is detected, Dependabot will publish a security alert, visible to repository/org admins in the GItHub UI.  Enabling automatic security updates is also an option for Dependabot; with this enabled, Dependabot will try to make the suggested fix on a branch and open a PR for that branch.  This automatic Dependabot security update …
=> Add CI support for Dependabot auto-generated security updates

package.json, yarn.lock
This PR addresses a dependabot alert.
See Dependabot alerts.
An alert was made against a package required by nightwatch.  While working on making that update, it was discovered that we are installing nightwatch (and chromedriver) in two places... the top level package.json and the tests/nightwatch/package.json.  There's no need to have it in both places.  This resolves one of the alerts by removing nightwatch and it's dependencies.
N/A
N/A
=> Remove testing packages from the top level

.github/github-lock.sh, .github/workflows/deploy.yml, .github/workflows/destroy.yml
This changeset fixes the incorrect branch locking behavior seen when the Destroy workflow runs.  Without this changeset, the Destroy workflow will always (pretty harmlessly) lock against the master branch.
Closes #144 
The [github-lock.sh script](https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/.github/github-lock.sh) plays an important role in our Deploy and Destroy workflows.  It's purpose is to prevent concurrent deploys or destroys against a single set of infrastructure.  For example, if someone pushes a change to the _mydev_ branch, a deployment will start that will build/configure the application in AWS; if someone pushes another change to _mydev_ before the first deployment finishes, you have potential for unpredictable behavior as two deployments are deploying …
=> Fix incorrect branch locking behavior for Destroy workflow

tests/nightwatch/package.json, tests/nightwatch/yarn.lock
Night watch test is failing in all environment. This PR is to address this issue.
Error: An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports 
Chrome version 88"
After further troubleshooting, it was realized that the chrome driver version(88) does not match the chrome browser version(90) which recently got upgraded during github actions runner update.
Closes #193 
The chrome driver version was upgraded from 88 to 90 to fix this issue
=> upgrading chromedriver from 86 to 90

services/app-api/serverless.yml
The purpose of this fix it to resolve warmup issue encountered in higher environment, when lambda failed to deploy.
The root cause is that the warmup plugin's enablement is conditional. Currently, the deploy looks for an SSM parameter that indicates a generic "infrastructure type". By default, warmup is disabled in lower environment and enabled in higher environments.
To resolve the issue, there should be global enablement of warmup, But setting the configuration of warmup should still be configurable
Closes #171 
The current logic to enable/disable warmup should be removed.
The configuration of warmup should have defaults but be configurable via SSM. So, warmup can never be shut off, but we can optionally warmup more or often.
Reviewed the following GitHub pages to understand the issue …
=> Enable lambda warmup for all Envs

.github/build_vars.sh, .github/workflows/deploy.yml
The purpose of this pull request is to allow unit tests to run within the pipeline without conceding that your repository must be wired to code climate.  Previously the stage was all in one (run unit tests, upload code coverage metrics). Now unit tests run first and the upload test coverage step is conditionally run based on an environment variable  (CODE_CLIMATE_ID) being set. If the env var is not set the step does not run. 
closes #221 
Only run the "publish test coverage to code climate" step if the "CODE_CLIMATE_ID" env var is set.
=>  Make Code climate upload conditional and archive coverage file

services/ui-auth/serverless.yml
A change was pushed earlier https://github.com/CMSgov/macpro-quickstart-serverless/pull/215 which is meant to add users at deploy time.  However, this code was developed and deployed locally.  This worked developing locally and tested in the target branch. However, when pushed to the pipeline there are differences in the github runner and a local bash shell.  This is to fix that issue. 
closes #227 
Fix syntax, push and let it run in the github runner. Log in and test in the cloudfront URL for the target environment. 
- [ x] This PR has an associated issue or issues.
- [x ] The associated issue(s) are linked above.
- [x ] This PR meets all acceptance criteria for those issues.
- [x ] This PR and linked issue(s) are adequately documented
- [x ] This PR and linked issues(s) are a complete …
=> Fixing syntax in ui-src/serverless.yml which prevented user creation 

services/ui-src/src/libs/helpers.js, services/uploads/serverless.yml
Currently the s3 bucket allows any file type to be uploaded. We have ClamAV scanning to scan and flag malicious files however during Pen Testing one of the actions taken is to upload an html file with Javascript code embedded in the html. This is marked as a high finding on the Pen Test and must be resolved before promoting to production. This issue is to address that finding by limiting the file types that can be uploaded from within the application.
Closes #187 
The UI should do a file type check based on the file extension. If the file selected to upload is not an allowed file type then the UI will flag the file and not allow a submit action. In addition to the react file type check the s3 bucket policy should be updated to only allow the same list of file types.
Updated ReactJS code …
=> Added to To Limit file type for s3 uploads

services/uploads/serverless.yml
The quickstart application makes use of two buckets, both of which are deployed from the uploads service:
1. The attachments bucket this is where user uploads are stored.
2. The clamav definitions bucket: this holds clamAV vulnerability definitions, and is used as part of the virus scanning strategy.
Neither of these buckets are encrypted.
The purpose of this fix is to achieve the following acceptance criteria:
The attachments bucket in the uploads service has server-side encryption enabled.
The clamAV definitions bucket in the uploads service has server-side encryption enabled.
Closes #234 
The approach to resolving the issue is by modifying the underlying CloudFormation code in the uploads services' serverless.yml file to enable encryption. The SS#-s3 encryption were enabled on the …
=> Enable encryption for the uploads service's buckets

services/ui/serverless.yml
This implements HTTP Strict Transport Security on our applications frontend Cloudfront Distribution and meets a compliance requirement
Closes #244
This issue was to implement HTTP Strict Transport Security for our web application.  Our frontend is a static React website hosted in S3 and fronted by Cloudfront, so this issue called for a mechanism for adding Headers to a Cloudfront response. 
Modifying Cloudfront headers is possible using [CloudFront Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html).  This is a new component of Cloudfront, and our header manipulation case is a perfect candidate for it.
This changeset adds a javascript function that takes a Cloudfront response and adds the "strict-transport-security" header.  This …
=> Implement HSTS on Cloudfront distribution - CloudFront Functions approach

.github/workflows/deploy.yml, package.json, services/output.sh, services/ui-src/package.json, services/ui-src/src/config.js, services/ui-src/yarn.lock, yarn.lock
This changeset addresses several published Dependabot alerts.  
Closes #236 
Any Dependabot alerts that could be fixed by updating packages were fixed.
Notably:
- The react-scripts package in the ui-src service was upgraded to latest.  The jest configuration needed to be modified to fix path requirements for the code climate uploader plugin.  A minor modification was made to the react's config.js script, to accommodate a react warning in the console.
- The serverless framework was updated to latest.  The output.sh script, which runs on top of the serverless info command, was modified to pass a --verbose flag instead of -v.  The -v flag no longer works with this latest version of serverless.
This PR is intentionally sparse as discussion about remaining issues should not occur here.
N/A
N/A
=> Dependencies - address several Dependabot alerts.

services/app-api/serverless.yml, services/stream-functions/serverless.yml, services/ui-auth/serverless.yml, services/ui/serverless.yml, services/uploads/serverless.yml
This changeset moves our Lambda roles to be built by Serverless using the native IAM configuration it offers, and removes the Lambda roles explicitly defined in Cloud formation.
Closes #265 
Following the [Serverless docs for IAM configuration](https://www.serverless.com/framework/docs/providers/aws/guide/iam/), existing Lambda roles were migrated from Cloudformation to the provider.iam configuration block.  The net result is the same, but it uses a lot less code.  
N/A
N/A
=> Leverage Serverless IAM configuration for role creation

destroy.sh
This changeset fixes a bug (introduced by bucket versioning #274) with the destroy script, and speeds things up signifcantly.
Closes #141 
Bug Fix against / related to:  #274 
As stated in the linked issue, bucket versioning broke the destroy functionality.  
These changes modify how buckets are emptied prior to cloudformation stacks being removed.  Now, the script removes all object versions and delete markers, a requirement to delete the bucket.
While working on this, I changed the way this script discovered buckets.  Previously, the script found all buckets, then looked for those with a STAGE tag that matched the target stage.  Tags can only be found by making calls for an individual bucket, which meant the script took a long time to run.  Now, the script iterates over the target …
=> Fix and significantly speed up the destroy script

services/ui/serverless.yml
There is a line trying to find the cloudfront domain name through an environment file we are phasing out. And defaults to a blank string thus overwriting the parameter if nothing is found.
=> Update Cloudfront domain name reference

package.json, yarn.lock
This changeset updates the version of [serverless-s3-bucket-helper](https://github.com/cmsgov/serverless-s3-bucket-helper) in use to 0.1.0.  Using the 0.1.0 release of [serverless-s3-bucket-helper](https://github.com/cmsgov/serverless-s3-bucket-helper) (see upstream PR/Issue https://github.com/CMSgov/serverless-s3-bucket-helper/pull/4) will remediate this project's S3.8 findings in Security Hub.
Closes #309 
The changes in serverless-s3-bucket-helper's 0.1.0 release were specifically designed to meet S3.8 requirements.  Please see the upstream's PR/Issue for details.  
In short, all buckets will have 'block public access' settings set to true by default.  So, by using the new version of this plugin, all buckets made by the application or its underlying deployment tooling will be S3.8 …
=> Remediate S3.8 Security Hub Finding - upgrade serverless-s3-bucket-helper to 0.1.0

package.json, yarn.lock
This updates the version of the serverless-s3-bucket-helper plugin in use.  This latest version includes a bug fix we want.
Dependency update only, N/A
N/A
N/A
N/A
=> Dependency update:  serverless-s3-bucket-helper

.github/workflows/deploy-support.yml
PR #319 was merged with a development value in its codebase.  This value specifies for which branch/branches the github workflow should run, which is difficult to lock to master when working on a dev branch.  So I had pushed a change to tell the new workflow to run for my development branch, sechub, when it should be set to run on master.  This undoes that dev change.
I'm going to skip the rest of the standard PR template.
=> Integrate Security Hub - Fix

services/.sechub/handlers/sync.js
This changeset fixes #325; it adds Workflow Status filters to the sechub service's sync function, to match the filtering behavior of Security Hub's default view.
Closes #325 
Without this changeset, we match all Record State = ACTIVE findings.  But findings can be ACTIVE, as in valid, but have a Workflow Status value of SUPPRESSED or RESOLVED.  
We want to ignore SUPPRESSED or RESOLVED active findings.  This change adds filters to only select records with workflow status values of NEW or NOTIFIED (the other two possible statuses).  The net result is a set of filters that match the Security Hub's default view in the console, which makes sense.
N/A
N/A
=> Bug Fix - Add Workflow Status filters to sechub's sync function

services/.sechub/handlers/sync.js
This changeset fixes a bug with the sechub sync function, where adding issues to large project boards would not work as intended.
Closes #333 
As described in the issue, the current (before this changeset) sync function code did not consider getting a paginated reply from octokit's listCards method.  
The approach here is to add a helper method which will step through all pages, if more than one, in the reply. 
N/A
N/A
=> Consider paginated reply from octokit's listCards method

services/.sechub/handlers/sync.js
This changeset fixes a bug that affected consumers of the sechub service who deployed to multliple accounts
Closes #464 
The approach matches the proposed solution in the issue:
- A 'stage' label is attached to all github issues created by the sync function
- the getAllIssues function is updated to fetch all issues labeled 'security-hub' and '<stagename>'
With the above change, the 'close issues with no active finding' logic is fixed... the sync function will only manage github issues built by security hub for that stage/aws-account
I really wish the quickstart had multiple accounts.  This bug could have been anticipated, but we failed.  Multiple accounts are what surfaced it; wish that happened sooner.
=> Fix sechub bug around filtering issues by account

services/ui/serverless.yml, tests/nightwatch/package.json, tests/nightwatch/yarn.lock
This changeset enables encryption on two buckets that are missing encryption.  It resolves a pair of medium severity findings in security hub.
Closes #467 
As outlined in the #467, the cloudformation for the ui service was modified to enable encryption.  This will be a brief write up, as there's nothing more to it than that.
N/A
N/A
=> Enable encryption for ui react and waflogs buckets

services/ui/serverless.yml
Enabling logging on clodfront distribution to write the logs to an s3 bucket
Closes #487 
The approach is to create an s3 bucket to host the cloudfront logs and then enable logging on the cloudfront distribution in the quickstart repo to write the logs to the s3 bucket
=> Enabling cloudfront logs

tests/nightwatch/package.json, tests/nightwatch/yarn.lock
Nightwatch test failing because of dated chrome driver. This PR is to update the chrome driver from 96 to 98.
Closes #495 
Chrome driver will be updated to version 98 and nightwatch test will not fail.
=> updating chrome driver version to 98 to fix nightwatch test errors

tests/nightwatch/package.json, tests/nightwatch/yarn.lock
This is so dependencies of Nightwatch flagged by Dependabot can be upgraded.
=> upgrading chrome v98 to 100

.github/workflows/deploy.yml
This changeset is a fix related to https://github.com/CMSgov/macpro-quickstart-serverless/pull/530
The github action for cypress has some caching behavior that wasn't fully undertstood and was causing failure some of the time.
Related to https://github.com/CMSgov/macpro-quickstart-serverless/pull/530
The Cypress github action handles installation of Cypress, sometimes.  If it detects you're using github cachine, which we were, it will not install Cypress.  It expects Cypress to be at ~/.cache/Cypress.  So if you're using caching, but not caching ~/.cache/Cypress, you'll fail.
There were two options:
- Override the "you have a cache so i wont install" behavior and force the action to install Cypress, by specifying install:true in the action.  
- Start caching ~/.cache/Cypress
We went with …
=> Add Cypress to node cache to avoid failure

.github/workflows/deploy.yml
This fixes an issue related to https://github.com/CMSgov/macpro-quickstart-serverless/pull/530
In the test jobs, the 'set branch name' step did not account for dependabot branches, as seen in the deploy job
N/A, but related to https://github.com/CMSgov/macpro-quickstart-serverless/pull/530
The deploy job has a switch that makes dependabot branch names usable.  The test jobs did not have that switch correctly copied/pasted.  This simply updates the 'set branch name' steps to match.
We noticed this when dependabot branches had their tests failing.  It was tough to discover earlier.
N/A
=> Modify branch name setting to account for the dependabot switch

package.json, services/app-api/serverless.yml, services/ui/serverless.yml, yarn.lock
This will add the waf plugin to the quickstart. The purpose of the plugin is to make creating a waf with a set of sensible rules that all our projects can use.
https://qmacbis.atlassian.net/browse/OY2-20420
This removes the need to create your own web acls in projects and will enable a more trimmed down serverless.yml where web acls are needed.
https://github.com/CMSgov/serverless-waf-plugin
=> Add the Serverless Waf Plugin to the QuickStart
