.circleci/circle-lock.sh
.circleci/config.yml

Add build locking and cci 2.0 support

---

.circleci/config.yml

Migrating the lock logic to its own step.
Moving the filter logic to a single place.

Improvements to CircleCI config.yml

---

.circleci/config.yml
.circleci/ctkey.sh

Add CTKey support to enable CloudTamer users to deploy

---

services/ui-src/package-lock.json
services/ui-src/package.json
services/ui-src/src/App.js
services/ui-src/src/Routes.js
services/ui-src/src/containers/Profile.css
services/ui-src/src/containers/Profile.js

Closes #4 
The logged in user now sees their email in the top navbar.
The email is a dropdown, containing "User Profile" and "Logout"
The User Profile menu is populated from cognito info.  Name can be edited; phone number can be added/edited.
The phone number field is to demonstrate how the user info collected at sign up can be extended and stored in cognito.
An address might make sense here, but let's keep it broad.

Add Profile and ability to update user info

---

services/ui-src/configureLocal.sh

Add configureLocal.sh stage parameter

---

services/uploads-scan/serverless.yml

Run the definition uploader on deploy

---

.github/workflows/destroy.yml

This should have been removed in the 'remove ctkey' pull request

Remove a ctkey reference that got by me

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This pull request adds both a [pull request and issue template](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).  It closes #115 
We are striving for a better documented product.   We believe having a standard PR and Issue format will help in this endeavour.  The changes we make, how we make them, why we make them, and why we made them how we did is important.  These conventions made into templates should help capture more of the what/why/how/when.  It should help the author write a better PR and have an easier time doing it, and it should help the reviewer more completely understand the code.
Closes #115 
I googled 'github pull request templates' and followed the docs.  The file names 'PULL_REQUEST_TEMPLATE.md and ISSUE_TEMPLATE.md' …

Add a Pull Request and Issue template to .github

---

README.md

The purpose of this PR is to add the Codeclimate maintainability badge to the quickstart README for visibility and linkage.
Addresses one of the AC's in #126 but does not close the ticket
Repo is added through the Codeclimate UI (codeclimate.com). After the repository is added you get the maintainability badge URL from repo settings. URL is now added to the README for realtime "scoring" of the master branch. 
This is merely being added for visibility, actually addressing the findings is part of ticket #126 
For more about Code Climate maintainability see link below: 
https://docs.codeclimate.com/docs/maintainability

adding codeclimate maintainability build badge to the README

---

services/ui-src/src/App.js

This changeset fixes a navbar bug that appears when a user logs in for the first time.
Closes #51 
This bug fix replaces the label for the profile drop down menu with a static "My Account" string.
This is a simple approach to the issue, but is viewed as acceptable, because it fixes the bug without introducing any antipatterns.
Fixing the blank label issue while preserving the dynamic label was also developed.  See #164 
The approach to #164 was discussed quite a bit.  Please see that PR for more details.  To summarize:  The core issue was that setting the email was invoked via onEffect, which does not run a second time when going from / -> /login -> /.  #164 took the approach of "set the label (email) when rendering the page, not when onEffect".  Those changes worked.  But, it wasn't …

Fix Navbar bug where dropdown label is blank on first login - static approach

---

services/ui-src/src/containers/Profile.js
services/ui-src/src/libs/user.js

This fixes the 'My Profile' functionality for the locally deployed app.
Closes #166 
The issues/steps involved were:
- The immediate error, as seen in #166 screenshot, is that the Profile container is getting userInfo by making a call to Cognito with the Auth library.  That won't work locally, as Auth is not connected to any real Cognito backend.  This was fixed by using the users library to get the current user's info.  That library includes a switch that says "if i'm running locally, send back the userInfo json object as it exists in local storage.... if i'm not running locally, make the call to Cognito via Auth".  This wrapper library was introduced as part of the local development workflow, and we're simply using it here.
- The next error was updating user attributes.  Similiar to the …

Fix the 'My Profile' functionality for locally deployed app

---

services/ui-src/src/containers/Profile.js
services/ui-src/src/libs/user.js

This reverts commit b3df5d5513595c378b7a5dc3ffebd0cf3f6003a6.
It was discovered, post merge, that #167 fixed local but broke Amazon.
My testing was inadequate, and I should have caught it.
N/A
This will be reverted, #166 will be reopened, and a new PR will eventually be made.
N/A
In Amazon deployed envs, updates to user attributes are not actually affected in Cognito.  The app functions, and it looks like it accepted the updated, but the call to Cognito is failing without throwing errors (outside of the console).

Revert "Fix my profile functionality for local development (#167)"

---

.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.production.md
.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.val.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.t128a.md
README.md

Normally, when promoting to val, a user creates a PR from master to val. When promoting to production, a user creates a PR from val to production.
The purpose of this enhancement is to automate the promotion of branches from master to val to production.
Closes #128 
The goal of this enhancement is to use branch specific github pull request templates and query parameters, clickable buttons can be made in the README that launch a PR for specific branches from a specific template; the specifics are the query parameters.
Added pull request templates for val and Prod into the .GitHub directory, in order to store the files in a hidden directory.
Updated the pull_request_template.{env}.md from an existing template
Reviewed the following documentations, repos and previous tasks to complete this …

Add 'Release' buttons for Val and Pod Release

---

.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.production.md
.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.val.md
README.md

This Pull Request affects a release from master to val.
This is an enhancement to add 'Release' buttons for Val and Prod
_There is no explicit post release checklist_
_If there are post release items specific to this release, you make your own checklist below_
_- [ ] example checklist item 1_
_- [ ] example checklist item 2_
_If there are no explicit post release items, you may put N/A for this section_

Release to Val

---

.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.production.md
.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.val.md
README.md

This Pull Request affects a release from val to production.
This is an enhancement for Release Buttons for PR to Val and Prod
_There is no explicit post release checklist_
_If there are post release items specific to this release, you make your own checklist below_
_- [ ] example checklist item 1_
_- [ ] example checklist item 2_
_If there are no explicit post release items, you may put N/A for this section_

Release to Production

---

services/ui-auth/serverless.yml

This changeset fixes a bug that caused users who signed up with Cognito to be unable to submit new amendments.
Closes #225 
As said above and in the issue, users who signed up with Cognito had been unable to submit new amendments.
The root cause of this issue was that the new Cognito signup did not collect First and Last names of users.  The user could sign up just fine, and authenticate to the app, but they had no first/last name.
So when the user went to submit an amendment, the First and Last names were blank.  These fields are also disabled, so they can't be edited.
This PR fixes the root issue by setting first/last names as required attributes.  Cognito now collects this data on signup, and users can submit amendments once again.  Screenshots attached.
new signup... note the …

Make first/last names required on signup - fix bug

---

services/app-api/package.json
services/app-api/serverless.yml
services/app-api/yarn.lock

CMS performs a number of cloud compliance scans, in particular a prowler scan was run against our accounts and identified a number of findings. One of those findings was that logging was not enabled on api gateway for each stack. The purpose of this ticket is to enable logging and resolving the finding.
closes #232 
Serverless offers a built in logging capability (https://www.serverless.com/blog/framework-release-v142). However, due to CMS permission boundary restrictions we cannot use that capability due to under the hood IAM actions. Another serverless plugin was discovered that implemented logging https://github.com/paulSambolin/serverless-enable-api-logs.  Logging was simply enabled by adding the plugin and adding the plugin dependencies. This does enable logging on existing api …

Enable API Gateway Logging via Serverless Plugin

---

package.json
services/app-api/handlers/create.js
services/app-api/libs/dynamodb-lib.js
services/app-api/package.json
services/app-api/yarn.lock
yarn.lock

This changeset resolves three Dependabot alerts.
Administrators can view the Alerts addressed by this PR in the Security panel.
This is a continuation of #252 and #236 
A [yarn resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) was used to override the version of xmlhttprequest-ssl way down the dependency tree.  This package is only used ultimately by the @serverless/platform-client-china package, so it's thought to be a non issue and a good candidate for resolution.  
A yarn resolution was also used to override the version of lodash the serverless-api-logs plugin uses.  No adverse effects have been noticed, and the plugin appears to be functioning normally.
The approach to incrementing our dynamodb atomic counter table has been changed, to remove the reliance …

Dependencies - resolve three dependabot alerts

---

package.json
services/ui-src/yarn.lock
yarn.lock

This changeset resolves a current dependabot, as well as cleans up a previous fix for a Dependabot alert.
Administrators can view the Alerts addressed by this PR in the Security panel.
This is a continuation of #252 #236 and #252 
The top level yarn lock file was regenerated to install latest packages, which resolved removed our need to add a yarn resolution for xmlhttprequest-ssl
The ui-src yarn lock was regenerated, resolving our (currently) last dependabot alert.
Referenced https://github.com/facebook/create-react-app/issues/10762
N/A

Dependencies - Resolve Dependabot alerts and maintenance

---

package.json
services/ui-auth/serverless.yml
services/ui-waflog-s3-bucket/serverless.yml
services/ui/serverless.yml
services/uploads/serverless.yml
yarn.lock

Added s3 versioning to all custom and serverless s3  buckets

---

package.json
services/ui-auth/serverless.yml
services/ui-waflog-s3-bucket/serverless.yml
services/ui/serverless.yml
services/uploads/serverless.yml
yarn.lock

S3t233c to testmerge3

---

.pre-commit-config.yaml
services/app-api/libs/dynamodb-lib.js
services/ui-auth/handlers/createUsers.js
services/ui-auth/serverless.yml
services/ui-src/src/Routes.js

This changeset adds a detect-secrets pre-commit hook and resolves all current findings.
Closes #277 
Since pre-commit is already configured in the repository, and since our 'pre-comit' PR workflow already runs all hooks, the approach was simple... add [detect-secrets](https://github.com/Yelp/detect-secrets) to our pre-commit config.
[Detect-secrets](https://github.com/Yelp/detect-secrets) checks for a wide range of secret types in source code.  Developers who run 'pre-commit install' in the respository will be unable to commit any secrets found by the hook, thus preventing secrets from getting into source.  However, since we cannot ensure developers will run 'pre-commit install' and use the hooks, we also run all pre-commit hooks against all files as part of a PR check.  So, if secret …

Add detect-secrets pre-commit hook

---

services/app-api/serverless.yml
services/ui/serverless.yml
tests/nightwatch/package.json
tests/nightwatch/yarn.lock

This PR is to merge master changes(cloudfront logging,chrome driver update to 98 and api gateway tracing)
This resolves vulnerabilities in val branch

Merge master branch into Val

---

services/app-api/serverless.yml
services/ui/serverless.yml
tests/nightwatch/package.json
tests/nightwatch/yarn.lock

This PR is to merge master changes(cloudfront logging,chrome driver update to 98 and api gateway tracing)
This resolves vulnerabilities in fievoheight branch

merge master into fiveoheight

---

package.json
services/app-api/package.json
services/app-api/serverless.yml
services/app-api/yarn.lock

Clientcert

---

services/ui-src/src/Routes.js
services/ui-src/src/containers/Amendments.js
services/ui-src/src/containers/NewAmendment.js
services/ui-src/src/libs/file.js

Refactored some file util imports and fix attachment bug

Dw upload fix

---

.githooks/pre-commit
dev

Create a pre-commit hook that runs our Prettier linter before files are commited.
Standard Git hooks are stored in `.git/hooks`, a directory not managed by source control. This PR creates a directory `.githooks` that will be included in source control, adds a command to the `dev` script to move the contents to `.git/hooks`, and adds a simple hook to run the Prettier linter.
Any future hooks or changes to the `.githooks` directory will be reflected in `.git/hooks` whenever the user runs the `./dev local` command.
- Briefly run `./dev local` to make sure hooks are copied to `.git/hooks`
- You can cancel the command as soon as it starts installing packages
- Make an egregious change to a file that should be watched by Prettier. (e.g. add a bunch of whitespace to App.tsx)
- Stage the change
- …

Add .githooks and pre-commit hook

---

services/app-api/serverless.yml
services/proxy-api/serverless.yml

We were making two WAF instances from plugin and initial serverless configuration. This removes the previous method in favor of the new. 

remove previous waf implementation, rely on plugin approach
